import math
print("values for 0 degrees")
print(math.sin(math.radians(0))) 
print(math.cos(math.radians(0)))
print(math.tan(math.radians(0)))
print("values for 30 degrees")
print(math.sin(math.radians(30)))
print(math.cos(math.radians(30)))
print(math.tan(math.radians(30)))
print("values for 45 degrees")
print(math.sin(math.radians(45)))
print(math.cos(math.radians(45)))
print(math.tan(math.radians(45)))
print("values for 60 degrees")
print(math.sin(math.radians(60)))
print(math.cos(math.radians(60)))
print(math.tan(math.radians(60)))
print("values for 90 degrees")
print(math.sin(math.radians(90)))
print(math.cos(math.radians(90)))
print(math.tan(math.radians(90)))
print("values for 180 degrees")
print(math.sin(math.radians(180)))
print(math.cos(math.radians(180)))
print(math.tan(math.radians(180)))
print("values for 270 degrees")
print(math.sin(math.radians(270)))
print(math.cos(math.radians(270)))
print(math.tan(math.radians(270)))
print("values for 360 degrees")
print(math.sin(math.radians(360)))
print(math.cos(math.radians(360)))
print(math.tan(math.radians(360)))
print("=============================")
print("values for 0 degrees")
print(1.0/(math.cos(math.radians(0))))
print("values for 30 degrees")
print(1.0/(math.sin(math.radians(30))))
print(1.0/(math.cos(math.radians(30))))
print(1.0/(math.tan(math.radians(30))))
print("values for 45 degrees")
print(1.0/(math.sin(math.radians(45))))
print(1.0/(math.cos(math.radians(45))))
print(1.0/(math.tan(math.radians(45))))
print("values for 60 degrees")
print(1.0/(math.sin(math.radians(60))))
print(1.0/(math.cos(math.radians(60))))
print(1.0/(math.tan(math.radians(60))))
print("values for 90 degrees")
print(1.0/(math.sin(math.radians(90))))
print(1.0/(math.cos(math.radians(90))))
print(1.0/(math.tan(math.radians(90))))
print("values for 180 degrees")
print(1.0/(math.sin(math.radians(180))))
print(1.0/(math.cos(math.radians(180))))
print(1.0/(math.tan(math.radians(180))))
print("values for 270 degrees")
print(1.0/(math.sin(math.radians(270))))
print(1.0/(math.cos(math.radians(270))))
print(1.0/(math.tan(math.radians(270))))
print("values for 360 degrees")
print(1.0/(math.sin(math.radians(360))))
print(1.0/(math.cos(math.radians(360))))
print(1.0/(math.tan(math.radians(360))))
