x=int(input("enter numeric value for numerator:"))
y=int(input("enter numeric value for denominator:"))
print('Result of long division is',x/y)
print('Remainder after long division is',x%y)
print('Result of floor division is',x//y)
